nome = str(input('Digite seu nome completo: ')).strip()
dividido = nome.split()
print('Analisando o seu nome...')
print(f'Seu nome em maiúsculas é {nome.upper()}.')
print(f'Seu nome em minúsculas é {nome.lower()}.')
print(f'Seu nome tem ao todo {len(nome) - nome.count(" ")}.')
print(f'Seu primeiro nome é {dividido[0]} e tem {len(dividido[0])} letras.')